server:
  port: 8060

management:
  tracing:
    sampling:
      probability: 1.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: #insert the name of the service
#            uri: lb://  #insert the name of the service
#            predicates:
#              - Path=/ #insert the name of the service   than add /**
#          - id: #insert the name of the service
#            uri: lb:// #insert the name of the service
#            predicates:
#              - Path=/ #insert the name of the service than add /**